import React from 'react';
import { HelpCircle, BookOpen, MessageSquare, ShieldCheck, Terminal } from 'lucide-react';

export const SupportView: React.FC = () => {
  const faqs = [
    {
      q: 'How does Truvix AI detect text generated by modern LLMs?',
      a: 'Truvix AI analyzes linguistic vectors including perplexity (predictability of token sequences) and burstiness (rhythmic sentence length variation). Human writing naturally exhibits high variance, whereas LLMs generate uniform, predictable text.'
    },
    {
      q: 'Can the image forensic engine detect Midjourney and DALL-E 3 images?',
      a: 'Yes. The image forensic module extracts noise maps, analyzes metadata signatures, and identifies micro-pixel artifacts caused by generative diffusion models.'
    },
    {
      q: 'Is my data stored or used to train models?',
      a: 'No. All uploaded text and image payloads are processed ephemerally in server memory and discarded immediately after report generation.'
    },
    {
      q: 'How accurate is the probability score?',
      a: 'Our models are calibrated across a benchmark dataset of over 500,000 human and AI-generated samples, achieving a 98.4% detection rate.'
    }
  ];

  return (
    <div className="p-6 lg:p-10 max-w-6xl mx-auto space-y-8 font-body">
      {/* Title */}
      <div className="border-b border-[#334155]/40 pb-6">
        <h1 className="text-3xl font-bold font-headline text-white tracking-tight">Support & Methodology</h1>
        <p className="text-sm text-[#c7c4d7] mt-1">Learn how our forensic models work and get technical assistance.</p>
      </div>

      {/* FAQs */}
      <div className="bg-[#1e293b] rounded-2xl border border-[#334155] p-6 lg:p-8 space-y-6 shadow-xl">
        <div className="flex items-center gap-3 border-b border-[#334155]/40 pb-4">
          <HelpCircle className="w-5 h-5 text-[#8083ff]" />
          <h3 className="font-headline font-semibold text-lg text-white">Frequently Asked Questions</h3>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {faqs.map((item, idx) => (
            <div key={idx} className="bg-[#131b2e] p-5 rounded-xl border border-[#334155]/60 space-y-2">
              <h4 className="font-headline font-semibold text-sm text-white">
                {item.q}
              </h4>
              <p className="text-xs text-[#c7c4d7] leading-relaxed">
                {item.a}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* API Reference Block */}
      <div className="bg-[#1e293b] rounded-2xl border border-[#334155] p-6 lg:p-8 space-y-4 shadow-xl">
        <div className="flex items-center gap-3 border-b border-[#334155]/40 pb-4">
          <Terminal className="w-5 h-5 text-[#009ada]" />
          <h3 className="font-headline font-semibold text-lg text-white">API Integration Reference</h3>
        </div>

        <p className="text-xs text-[#c7c4d7] leading-relaxed">
          Integrate automated forensic scans directly into your content moderation workflow via our JSON endpoint:
        </p>

        <pre className="bg-[#0b1326] border border-[#334155] p-4 rounded-xl text-xs font-mono text-[#c0c1ff] overflow-x-auto">
{`POST /api/analyze-text
Content-Type: application/json

{
  "text": "Payload to analyze for AI generation patterns..."
}`}
        </pre>
      </div>
    </div>
  );
};
